### ISSUE TITLE
Cache credentials

### ISSUE THREAD

**Issue by gillesgw** [php-opencloud/openstack#135]
I'm trying to keep credentials cached from one request to another, but the documentation seems to be out of date on this topic : http://php-opencloud.readthedocs.io/en/latest/caching-creds.html

The methods importCredentials() and exportCredentials() doesn't exists anymore (It does in rackspace lib)

**Comment by haphan** [comment]
@gillesgw You are right. This feature is lacking in this SDK and relate to issues #40  and #100.

**Comment by gillesgw** [comment]
Okey, so for now the only solution is to switch to rackspace/php-opencloud ?

**Comment by haphan** [comment]
Can you briefly describe your use case?

**Comment by gillesgw** [comment]
I use swift object storage in a project (I'm new to this), and testing it for using it in any project in the future. My current project is a Symfony3 project; it works perfectly when I have a few pictures in a page; But in my specific use case I have some galleries with several dozen of pictures : the first pictures are loaded okey but then I get a 429 to many request on the auth url (My provider is OVH).

I would also like to cache token for speed reasons...

**Comment by weknowsoftware** [comment]
Hi @haphan I have a similar requirement - I have a UI which needs to carry out operations on the user's stack and need to persist the credentials in the session between different requests (the user navigates through their stack via my UI). I can't serialize the OpenStack object as it contains closures, so I'm ending up re-authenticating in each session. Previously I was using rackspace/php-opencloud and was able to do this.
Without this capability php-opencloud is simply not fast enough for a production-ready UI.
I note this issue was closed without further comment, can you please clarify? Thanks.

**Comment by gillesgw** [comment]
Hi @weknowsoftware, do you use this only for object storage ? If so, I made a very simple lib for that; It's far from perfect because I just don't have the time. I need to improve this, write tests, doc... But it handle simple auth caching, if you want I could past you an example.

https://github.com/kabolt/php-swift

Maybe for many php-opencloud operation, auth caching is not an issue, but for swift storage it's just useless without this...

**Comment by weknowsoftware** [comment]
Hi @gillesgw, thanks for this. Unfortunately, I'm not using Swift, I'm using keystone/nova/ironic/heat. It's an issue for me as I don't want to keep obtaining a new token for each call, but I have no way of extracting them/re-inserting them into an OpenStack object...

**Comment by haphan** [comment]
This issue is being addressed in PR #175

**Comment by haphan** [comment]
@weknowsoftware @gillesgw Exporting authentication token is possible since v2.0.15 thanks to #175 

Hope it helps.
