### ISSUE TITLE
Is this code still being maintained?

### ISSUE THREAD

**Issue by karenmt** [php-opencloud/openstack#355]
The last update was in 2021, and some of the dependencies are preventing me from updating other packages and frameworks.

**Comment by k0ka** [comment]
@haphan 

This package is incompatible with the latest Laravel 9 due to package `guzzlehttp/uri-template` (https://github.com/chrisnharvey/flysystem-openstack-swift/issues/36)

Could you merge https://github.com/php-opencloud/openstack/pull/356 to fix this problem?

**Comment by tcarpenter2014** [comment]
Hi,

I too am waiting for this fix to occur.

When will this be merged to fix the outdated guzzlehttp/uri-template 0.2 requirement in the current release of the package?

Trying to install the latest php-opencloud/openstack package on latest version of Laravel 9/10 will result in failed composer install because of the outdated guzzlehttp/uri-template requirement.

Thanks.

**Comment by lucasvdh** [comment]
Lets hope @jamiehannaford or @haphan will merge @LiamBull's PR.

Until that time you can use his fork as a substitute:

```json
{
  "require": {
    "php-opencloud/openstack": "dev-upgrade-uri-template",
  },
  "repositories": [
    {
      "type": "vcs",
        "url": "https://github.com/vanillaops/openstack"
      }
  ],
}
```

Or if you have other dependencies that rely on a specific version of `php-opencloud/openstack` you could also use my fork of @LiamBull which is tagged:

```json
{
  "require": {
    "php-opencloud/openstack": "3.2.1",
  },
  "repositories": [
    {
      "type": "vcs",
        "url": "https://github.com/dossierdata/openstack"
      }
  ],
}
```

**Comment by k0ka** [comment]
It looks like this package is completely abandoned. The package was maintained by rackspace.com. Both old authors are not working on rackspace anymore. I tried to contact both sdk@ and support@ rackspace.com without any success.

**Comment by karenmt** [comment]
I contacted Rackspace in February, and they do not maintain any SDKs.  This was their response:

> we no longer maintain our own PHP SDKs and have been recommending the usage of the php-opencloud SDK which is managed by the Openstack community.  

> If you'd like, you could reach out to them via their Issues section within Github to see if they can assist with your issue or provide further info on whether it is actively maintained:

They then provided a link to this project's issues page.

**Comment by lucasvdh** [comment]
That would be a shame. 

@karenmt seeing as how you've already been in contact with Rackspace, would you be willing to try and contact them again to see if they can still manage the php-opencloud organization? 

If they do still have access it would be great if they could transfer ownership back to the community. For example to someone who has previously contributed to this repo and is willing to maintain it or at least accept PR's.

This is all under the assumption that @jamiehannaford and @haphan are no longer maintaining this repo though.

Otherwise we'd be stuck with hosting our own forks of this package and any other package that relies on it...

**Comment by karenmt** [comment]
I tried, and got this response:


> As per reviewing your request. Rackspace is not supporting https://github.com/php-opencloud/openstack and at this moment, and there are no future plans to have support on this project.
> Therefore, we have no contact with the dev team or any other relationship with this software or any SDK.

**Comment by jamiehannaford** [comment]
Hi there, sorry for the delay. I no longer maintain this codebase, but would be happy to add new maintainers to the org. Who would like to volunteer?

**Comment by k0ka** [comment]
Well, if no one is willing to do it, I can be that volunteer. 

Or you might just merge https://github.com/php-opencloud/openstack/pull/356 and publish package.

Or maybe @lucasvdh wants to take care of it as he already has his fork at https://github.com/dossierdata/openstack

**Comment by lucasvdh** [comment]
@jamiehannaford if you could add me to the org as a maintainer I will try my best to at least keep this code up to date with the latest dependencies.

**Comment by haphan** [comment]
@lucasvdh  and @k0ka I've invited you both as maintainers for this project. Thank you for leaning in to support.

**Comment by k0ka** [comment]
I semi-manually merged the fix. The travis-ci is not working anymore so the next step will be setting up the automatic testing again.
